version: "2"
services:
    dev:
        image: sat03
        ports:
            - 5173:5173
        volumes:
            - type: bind
              source: ./public
              target: /app/public
              read_only: true
            - type: bind
              source: ./src
              target: /app/src
              read_only: true
